logging:
  level:
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: info
    org.springframework: warn
    org.apache.catalina: warn
spring:
  main:
    web-environment: ${enable-web:true}