version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx1200m

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    - run: mvn verify

    - run:
        name: "Docker build"
        command: >
          mvn jib:build
          -Djib.to.auth.username=${DOCKER_USER}
          -Djib.to.auth.password=${DOCKER_PASSWORD}

    - run: |
        mkdir /tmp/artifacts
        cp target/*.jar /tmp/artifacts

    - store_artifacts:
        path: /tmp/artifacts

    - persist_to_workspace:
        root: /tmp/artifacts
        paths:
          - "*"

  publish-github-release:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish to Github"
          command: >
            ghr
            -t ${GITHUB_TOKEN}
            -u ${CIRCLE_PROJECT_USERNAME}
            -r ${CIRCLE_PROJECT_REPONAME}
            -c ${CIRCLE_SHA1}
            -delete
            ${CIRCLE_TAG}
            ./artifacts/

workflows:
  version: 2

  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/