# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

default: &default
  docker:
  - image: circleci/openjdk:8-jdk

  working_directory: ~/repo

  environment:
    MAVEN_OPTS: -Xmx1200m

jobs:
  build:
    <<: *default

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    - run: mvn test

  release:
    <<: *default

    steps:
    - checkout

    - setup_remote_docker

    - run: mvn deploy



workflows:
  version: 2
  un-tagged-build:
    jobs:
    - build:
        filters:
          tags:
            ignore: /^\d+\.\d+\.\d+/
  tagged-build:
    jobs:
    - release:
        filters:
          branches:
            ignore: /^\d+\.\d+\.\d+/
    tags:
      only: /^\d+\.\d+\.\d+/