version: 2.1

orbs:
  github: haskell-works/github-release@1.3.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx1200m

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    - run: mvn verify

    - run: |
        mkdir /tmp/artifacts
        cp target/*.jar /tmp/artifacts

    - store_artifacts:
        path: /tmp/artifacts

    - persist_to_workspace:
        root: /tmp/artifacts
        paths:
          - "*"

workflow:
  build_and_release:
    jobs:
      - build
      - github/release:
          tag: v$CIRCLE_BUILD_NUM
          title: Release v$CIRCLE_BUILD_NUM
          attach-workspace: true
          artefacts-folder: .
          requires:
            - build
          filters:
            branches:
              only: master
